#!/bin/bash

### auto-install mvncp for automatic dependency resolution if not yet present
if [ -z "$(which mvncp)" ]; then
    curl -s https://raw.githubusercontent.com/holgerbrandl/kutils/master/misc/kscript/mvncp > ~/bin/kscript && chmod u+x ~/bin/mvncp
fi

if [ -n "$1" ]; then
#    classpath=$(mvncp ${1/,/ } 2>/dev/null)
    classpath=$(mvncp $(echo "$1" | tr ',' " " | tr -d '"') 2>/dev/null)
fi
shift
echo kotlinc -script -classpath "$classpath" "$@"
